default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: library_dev

test:
  <<: *default
  database: library_test
